POS_TAG_TRANSLATIONS = {
    'NNG': 'Common Noun',
    'NNP': 'Proper Noun',
    'NNB': 'Dependent Noun',
    'NR': 'Numeral',
    'NP': 'Pronoun',
    'VV': 'Verb',
    'VA': 'Adjective',
    'VX': 'Auxiliary Predicate',
    'VCP': 'Positive Copula',
    'VCN': 'Negative Copula',
    'MM': 'Determiner',
    'MAG': 'General Adverb',
    'MAJ': 'Conjunctive Adverb',
    'IC': 'Interjection',
    'JKS': 'Subject Case Particle',
    'JKC': 'Complement Case Particle',
    'JKG': 'Genitive Case Particle',
    'JKO': 'Object Case Particle',
    'JKB': 'Adverbial Case Particle',
    'JKV': 'Vocative Case Particle',
    'JKQ': 'Quotative Case Particle',
    'JC': 'Conjunctive Particle',
    'JX': 'Auxiliary Particle',
    'EP': 'Pre-Final Ending',
    'EF': 'Final Ending',
    'EC': 'Connective Ending',
    'ETN': 'Nominal Ending',
    'ETM': 'Adnominal Ending',
    'XPN': 'Noun Prefix',
    'XSN': 'Noun Derivative Suffix',
    'XSV': 'Verb Derivative Suffix',
    'XSA': 'Adjective Derivative Suffix',
    'XR': 'Root',
    'SF': 'Period, Question Mark, Exclamation Mark',
    'SE': 'Ellipsis',
    'SS': 'Quotation Mark, Bracket, Dash',
    'SP': 'Comma, Middle Dot, Colon, Slash',
    'SO': 'Dash(물결,숨김,빠짐)',
    'SW': 'Other Symbol (Mathematical Symbols, Currency Symbols)',
    'SH': 'Hanja',
    'SL': 'Foreign Language',
    'SN': 'Number',
    'NF': 'Guessed Noun Category',
    'NV': 'Guessed Predicate Category',
    'NA': 'Unknown Category'
}

SIMPLIFIED_POS_TAGS = {
    'NNG': 'Noun', 'NNP': 'Noun', 'NNB': 'Noun', 'NR': 'Noun', 'NP': 'Noun',
    'VV': 'Verb', 'VA': 'Adjective', 'VX': 'Verb', 'VCP': 'Verb', 'VCN': 'Verb',
    'MM': 'Determiner',
    'MAG': 'Adverb', 'MAJ': 'Adverb',
    'IC': 'Interjection',
    'JKS': 'Particle', 'JKC': 'Particle', 'JKG': 'Particle', 'JKO': 'Particle', 
    'JKB': 'Particle', 'JKV': 'Particle', 'JKQ': 'Particle', 'JC': 'Particle', 'JX': 'Particle',
    'EP': 'Ending', 'EF': 'Ending', 'EC': 'Ending', 'ETN': 'Ending', 'ETM': 'Ending',
    'XPN': 'Prefix/Suffix', 'XSN': 'Prefix/Suffix', 'XSV': 'Prefix/Suffix', 'XSA': 'Prefix/Suffix', 'XR': 'Root',
    'SF': 'Punctuation', 'SE': 'Punctuation', 'SS': 'Punctuation', 'SP': 'Punctuation', 
    'SO': 'Punctuation', 'SW': 'Symbol',
    'SH': 'Foreign', 'SL': 'Foreign', 'SN': 'Number',
    'NF': 'Noun', 'NV': 'Verb', 'NA': 'Unknown'
}